spring:

  datasource:
    url: jdbc:h2:~/sondadb
    username: elo7
    password: 123
    driverClassName: org.h2.Driver

  jpa:
    show-sql: false
    format-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2